[workspace]

members = ["klang", "pyklang"]
resolver = "2"

[workspace.package]

version = "0.2.0"
edition = "2021"
description = "The Klang programming language"
authors = ["K-Scale Labs"]
repository = "https://github.com/kscalelabs/klang"
license = "MIT"
readme = "README.md"
