[package]

name = "klang"
version = "0.1.0"
authors = ["K-Scale Labs"]
edition = "2021"

[dependencies]

pest = "2.5"
pest_derive = "2.5"
thiserror = "1.0"
lazy_static = "1.4.0"

[[bin]]

name = "klang"
path = "src/main.rs"
